# Changes here will be overwritten by Copier
_commit: v2.0.5
_src_path: gh:lincc-frameworks/python-project-template
author_email: awoldag@uw.edu
author_name: Drew Oldag
create_example_module: true
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: resspect_external
project_license: MIT
project_name: resspect_external
project_organization: lsstdesc
python_versions:
- '3.9'
- '3.10'
- '3.11'
- '3.12'
- '3.13'
